#!/usr/bin/env python3
"""Content insights over the consolidated corpus: what the scanners actually
found — top vulnerabilities, most-flagged packages, the worst containers,
SBOM stats, secrets, misconfigurations, web/network findings.

Companion to figures.py (which compares scanners). Writes figures/INSIGHTS.md
plus a few bar charts. Usage: python scripts/insights.py [corpus_dir] [out_dir]
"""
from __future__ import annotations
import collections, csv, json, sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
CORPUS = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "out" / "_corpus"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "figures"
TOP = 30


def load(path: Path) -> list[dict]:
    rows = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return rows


def app_categories() -> dict[str, str]:
    out = {}
    p = ROOT / "data" / "inventory" / "d1.csv"
    if p.is_file():
        for r in csv.DictReader(open(p)):
            out[r["container"]] = r.get("category", "?")
    return out


def _bar(pairs, title, path, color="#46a", rot=70):
    pairs = pairs[:25]
    fig, ax = plt.subplots(figsize=(11, 5))
    ax.bar([str(k) for k, _ in pairs], [v for _, v in pairs], color=color)
    ax.set_title(title)
    plt.xticks(rotation=rot, ha="right", fontsize=7)
    fig.tight_layout(); fig.savefig(path, dpi=120); plt.close(fig)


def main() -> int:
    fp = CORPUS / "findings.jsonl"
    if not fp.is_file():
        print(f"error: {fp} not found", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    print(f"loading {fp} ...")
    f = load(fp)
    apps = app_categories()
    print(f"{len(f):,} findings")
    L = ["# multiscan — content insights", "",
         "What the scanners found, across the 130-container D1 corpus. "
         "Generated by `scripts/insights.py`.", "",
         f"- findings: **{len(f):,}**", ""]

    # ── most-found CVEs ─────────────────────────────────────────────────────
    cve_occ = collections.Counter()
    cve_ct = collections.defaultdict(set)
    cve_sc = collections.defaultdict(set)
    cve_cvss = collections.defaultdict(float)
    cve_pkg = {}
    for d in f:
        for c in (d.get("cves") or []):
            c = c.upper()
            cve_occ[c] += 1
            cve_ct[c].add(d.get("target_name", ""))
            cve_sc[c].add(d.get("scanner", ""))
            if isinstance(d.get("cvss"), (int, float)):
                cve_cvss[c] = max(cve_cvss[c], float(d["cvss"]))
            cve_pkg.setdefault(c, d.get("package", ""))
    L += ["## Most-found vulnerabilities (CVEs)", "",
          "| CVE | occurrences | containers | scanners | max CVSS | example pkg |",
          "|---|--:|--:|--:|--:|---|"]
    for c, n in cve_occ.most_common(TOP):
        L.append(f"| {c} | {n:,} | {len(cve_ct[c])} | {len(cve_sc[c])} | "
                 f"{cve_cvss[c] or '-'} | {cve_pkg.get(c, '')} |")
    _bar(cve_occ.most_common(25), "Top CVEs by occurrences", OUT / "I1_top_cves.png")

    # ── most-flagged packages ───────────────────────────────────────────────
    pkg_cves = collections.defaultdict(set)
    pkg_occ = collections.Counter()
    pkg_eco = {}
    for d in f:
        if d.get("category") != "pkg-vuln":
            continue
        p = (d.get("package") or "").strip()
        if not p:
            continue
        pkg_occ[p] += 1
        pkg_eco.setdefault(p, d.get("ecosystem", ""))
        for c in (d.get("cves") or []):
            pkg_cves[p].add(c.upper())
    L += ["", "## Most-flagged packages (pkg-vuln)", "",
          "| package | ecosystem | distinct CVEs | occurrences |",
          "|---|---|--:|--:|"]
    for p, n in sorted(pkg_occ.items(), key=lambda kv: -len(pkg_cves[kv[0]]))[:TOP]:
        L.append(f"| {p} | {pkg_eco.get(p, '')} | {len(pkg_cves[p])} | {n:,} |")
    _bar(sorted(((p, len(c)) for p, c in pkg_cves.items()), key=lambda kv: -kv[1]),
         "Top packages by distinct CVEs", OUT / "I2_top_packages.png", "#a64")

    # ── worst containers ────────────────────────────────────────────────────
    ct_cat = collections.defaultdict(collections.Counter)
    for d in f:
        ct_cat[d.get("target_name", "?")][d.get("category", "?")] += 1
    cats = ["pkg-vuln", "secret", "image-config", "other", "web-vuln",
            "network-vuln", "malware", "sbom-component"]
    L += ["", "## Worst containers — findings ranking", "",
          "| container | app type | total | " + " | ".join(cats) + " |",
          "|---|---|--:|" + "--:|" * len(cats)]
    ranked = sorted(ct_cat.items(),
                    key=lambda kv: -(sum(kv[1].values()) - kv[1]["sbom-component"]))
    for name, cc in ranked[:TOP]:
        tot = sum(cc.values())
        L.append(f"| {name} | {apps.get(name, '?')} | {tot:,} | "
                 + " | ".join(str(cc.get(c, 0)) for c in cats) + " |")
    _bar([(n, sum(cc.values()) - cc["sbom-component"]) for n, cc in ranked[:25]],
         "Containers by non-SBOM findings", OUT / "I3_worst_containers.png", "#c54")

    # ── findings by application type ────────────────────────────────────────
    by_app = collections.Counter()
    for d in f:
        by_app[apps.get(d.get("target_name", ""), "?")] += 1
    L += ["", "## Findings by application type", "",
          "| application type | findings |", "|---|--:|"]
    for a, n in by_app.most_common():
        L.append(f"| {a} | {n:,} |")

    # ── SBOM ────────────────────────────────────────────────────────────────
    sbom_ct = collections.Counter()
    comp_ct = collections.defaultdict(set)
    eco_ct = collections.Counter()
    for d in f:
        if d.get("category") != "sbom-component":
            continue
        t = d.get("target_name", "?")
        sbom_ct[t] += 1
        comp_ct[(d.get("package") or "").strip()].add(t)
        eco_ct[d.get("ecosystem") or "?"] += 1
    if sbom_ct:
        vals = sorted(sbom_ct.values())
        L += ["", "## SBOM", "",
              f"- components per container: median **{vals[len(vals)//2]:,}**, "
              f"max **{vals[-1]:,}**, min **{vals[0]:,}**", "",
              "Largest SBOMs:", "", "| container | components |", "|---|--:|"]
        for t, n in sbom_ct.most_common(15):
            L.append(f"| {t} | {n:,} |")
        L += ["", "Most common components (by containers):", "",
              "| component | containers |", "|---|--:|"]
        for c, ts in sorted(comp_ct.items(), key=lambda kv: -len(kv[1]))[:20]:
            L.append(f"| {c} | {len(ts)} |")
        L += ["", "Ecosystems:", "", "| ecosystem | components |", "|---|--:|"]
        for e, n in eco_ct.most_common():
            L.append(f"| {e} | {n:,} |")

    # ── secrets / config / web / network ────────────────────────────────────
    def top_by(cat, label, idkey="title"):
        occ = collections.Counter()
        ct = collections.defaultdict(set)
        for d in f:
            if d.get("category") != cat:
                continue
            k = (d.get(idkey) or d.get("id") or "?")[:70]
            occ[k] += 1
            ct[k].add(d.get("target_name", ""))
        if not occ:
            return []
        out = ["", f"## {label}", "", "| finding | occurrences | containers |",
               "|---|--:|--:|"]
        for k, n in occ.most_common(TOP):
            out.append(f"| {k} | {n:,} | {len(ct[k])} |")
        return out

    L += top_by("secret", "Secrets — by type", "id")
    L += top_by("image-config", "Image misconfigurations", "title")
    L += top_by("other", "SAST findings — by rule", "id")
    L += top_by("web-vuln", "Web vulnerabilities (DAST)", "title")
    L += top_by("network-vuln", "Network — OpenVAS NVTs", "title")
    L += top_by("malware", "Malware / IOC hits", "title")

    (OUT / "INSIGHTS.md").write_text("\n".join(L) + "\n")
    print(f"wrote {OUT/'INSIGHTS.md'}  + I1/I2/I3 charts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
