#!/usr/bin/env python3
"""Generates config/os.yaml with the correct paths for THIS clone, without manual
editing. Output/cache paths: env OSCENSUS_OUT/OSCENSUS_CACHE, otherwise
scan-out/ inside the repo.
Run:  python3 scripts/render_config.py
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
def pick(env, rel):
    """Return the env var `env` if set, else ROOT/`rel`.

    Lets the output/cache directories be overridden per-clone (OSCENSUS_OUT,
    OSCENSUS_CACHE) while defaulting to a path inside this repo checkout.
    """
    return os.environ.get(env) or str(ROOT / rel)

OUT   = pick("OSCENSUS_OUT",   "scan-out/out_so")
CACHE = pick("OSCENSUS_CACHE", "scan-out/cache_so")
for d in (OUT, CACHE, str(ROOT/"work")):
    Path(d).mkdir(parents=True, exist_ok=True)

cfg = f"""# Generated by scripts/render_config.py (do not edit by hand; re-run the script).
queue:
  backend: sqlite
  sqlite_path: {ROOT}/work/os.db
source:
  type: jsonl
  path: {ROOT}/data/jobs_unique.jsonl
scanners:
  registry: {ROOT}/config/scanners.yaml
  only: [syft, cdxgen, trivy, grype, osv, clair, dockle, checkov,
         trufflehog, gitleaks, detect-secrets, whispers, clamav, yarahunter]
  static: true
  dynamic: false
output:
  dir: {OUT}
  cache_dir: {CACHE}
  keep_image_tarball: false
  skip_done: true
workers:
  count: 1            # one pull at a time per machine (network limit)
  scan_timeout: 1800
runtime:
  remove_image_after: true
  max_image_mb: 2000
  prune_every: 25
  scan_parallelism: 4
  pull_retries: 4
  pull_backoff: 30
  dockerhub_accounts: {ROOT}/config/accounts.json
"""
(ROOT / "config/os.yaml").write_text(cfg)
print(f"config/os.yaml generated. out={OUT} cache={CACHE}")
